"""Événements publiés par trust-safety (consommés à terme par listing/search/geo/crm/identity)."""
ACCOUNT_SUSPENDED = "account.suspended"
ACCOUNT_UNSUSPENDED = "account.unsuspended"
REPORT_CREATED = "report.created"
REPORT_RESOLVED = "report.resolved"
REPORT_DISMISSED = "report.dismissed"
