"""Événements publiés par rental (consommés par notification pour les emails)."""
MANDATE_CREATED = "rental.mandate.created"
MANDATE_SIGNED = "rental.mandate.signed"
LEASE_CREATED = "rental.lease.created"
LEASE_SIGNED = "rental.lease.signed"
RENT_PAID = "rental.rent.paid"
DEPOSIT_RETURNED = "rental.deposit.returned"
LEASE_REVISED = "rental.lease.revised"
CHARGE_REGULARIZED = "rental.charge_regularization.sent"
APPLICATION_RECEIVED = "rental.application.received"
