"""Routing keys des événements coloc-listing (exchange semsar.events)."""
LISTING_PUBLISHED = "coloc.listing_published"
LISTING_STATUS_CHANGED = "coloc.listing_status_changed"
LEASE_CREATED = "coloc.lease_created"
PAYMENT_STATUS_CHANGED = "coloc.payment_status_changed"
PAYMENT_INTENT_CREATED = "coloc.payment_intent_created"
PAYMENT_WEBHOOK_RECEIVED = "coloc.payment_webhook_received"
ETAT_DES_LIEUX_CREATED = "coloc.etat_des_lieux_created"
ETAT_DES_LIEUX_SIGNED = "coloc.etat_des_lieux_signed"
CANDIDATURE_RECEIVED = "coloc.candidature_received"
CANDIDATURE_ACCEPTED = "coloc.candidature_accepted"
