"""Add fields to leads table

Revision ID: 0bbb632ded0c
Revises: a6bda3fd6182
Create Date: 2026-01-21 00:34:53.987698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bbb632ded0c'
down_revision = 'a6bda3fd6182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('lost_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('qualified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lost_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lost_at')
        batch_op.drop_column('qualified_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('assigned_to_id')
        batch_op.drop_column('lost_reason')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
